package medtrack;

import java.awt.Dimension;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; 
import java.sql.SQLException;
import java.sql.Date;

public class StatistikData extends javax.swing.JFrame {
    private Connection connection;
    /**
     * Creates new form StatistikData
     */
    public StatistikData() {
        initComponents();
        connection = KoneksiApo.getKoneksi();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        menupanelMD = new javax.swing.JPanel();
        medtrackPanelMD = new javax.swing.JPanel();
        managerLabel = new javax.swing.JLabel();
        judulLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        idManagerLabel = new javax.swing.JLabel();
        btnMD = new javax.swing.JButton();
        btnStatistik = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        mainSDPanel = new javax.swing.JPanel();
        judulSD = new javax.swing.JLabel();
        grafikPanel = new javax.swing.JPanel();
        PenjualanPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menupanelMD.setBackground(new java.awt.Color(0, 93, 146));

        medtrackPanelMD.setBackground(new java.awt.Color(255, 255, 255));
        medtrackPanelMD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        medtrackPanelMD.setFocusCycleRoot(true);

        managerLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        managerLabel.setText("Manager");

        judulLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medtrackicon/medtrack.png"))); // NOI18N

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconmedtrack/icons8-businesswoman-94.png"))); // NOI18N
        iconLabel.setText("jLabel2");

        javax.swing.GroupLayout medtrackPanelMDLayout = new javax.swing.GroupLayout(medtrackPanelMD);
        medtrackPanelMD.setLayout(medtrackPanelMDLayout);
        medtrackPanelMDLayout.setHorizontalGroup(
            medtrackPanelMDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medtrackPanelMDLayout.createSequentialGroup()
                .addGroup(medtrackPanelMDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, medtrackPanelMDLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(medtrackPanelMDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(managerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idManagerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, medtrackPanelMDLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        medtrackPanelMDLayout.setVerticalGroup(
            medtrackPanelMDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medtrackPanelMDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(medtrackPanelMDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(medtrackPanelMDLayout.createSequentialGroup()
                        .addComponent(managerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idManagerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(iconLabel))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnMD.setBackground(new java.awt.Color(0, 93, 146));
        btnMD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMD.setForeground(new java.awt.Color(255, 255, 255));
        btnMD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/medicine-icon-29791.png"))); // NOI18N
        btnMD.setText("Management Data");
        btnMD.setIconTextGap(20);
        btnMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMDActionPerformed(evt);
            }
        });

        btnStatistik.setBackground(new java.awt.Color(52, 152, 219));
        btnStatistik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStatistik.setForeground(new java.awt.Color(255, 255, 255));
        btnStatistik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transaksi.png"))); // NOI18N
        btnStatistik.setText("Statistik Data");
        btnStatistik.setIconTextGap(20);
        btnStatistik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatistikActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setIconTextGap(10);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        mainSDPanel.setBackground(new java.awt.Color(255, 255, 255));

        judulSD.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        judulSD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulSD.setText("Statistik Data");

        grafikPanel.setBackground(new java.awt.Color(255, 255, 255));
        grafikPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                grafikPanelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        PenjualanPanel.setBackground(new java.awt.Color(255, 255, 255));
        PenjualanPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                PenjualanPanelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout mainSDPanelLayout = new javax.swing.GroupLayout(mainSDPanel);
        mainSDPanel.setLayout(mainSDPanelLayout);
        mainSDPanelLayout.setHorizontalGroup(
            mainSDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSDPanelLayout.createSequentialGroup()
                .addGroup(mainSDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainSDPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(grafikPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(PenjualanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainSDPanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(judulSD, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        mainSDPanelLayout.setVerticalGroup(
            mainSDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSDPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(judulSD)
                .addGap(37, 37, 37)
                .addGroup(mainSDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(grafikPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(PenjualanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(396, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menupanelMDLayout = new javax.swing.GroupLayout(menupanelMD);
        menupanelMD.setLayout(menupanelMDLayout);
        menupanelMDLayout.setHorizontalGroup(
            menupanelMDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelMDLayout.createSequentialGroup()
                .addGroup(menupanelMDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menupanelMDLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menupanelMDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStatistik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(menupanelMDLayout.createSequentialGroup()
                                .addComponent(medtrackPanelMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(menupanelMDLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(mainSDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        menupanelMDLayout.setVerticalGroup(
            menupanelMDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelMDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(medtrackPanelMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStatistik, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menupanelMDLayout.createSequentialGroup()
                .addComponent(mainSDPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(menupanelMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 245, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menupanelMD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMDActionPerformed
        // TODO add your handling code here:
        new MObatManager().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMDActionPerformed

    private void btnStatistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistikActionPerformed
        // TODO add your handling code here:
        new StatistikData().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStatistikActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin akan keluar?", "PERINGATAN", dialogBtn);

        if(dialogResult==0){
            //True condition
            System.exit(0);
            new LoginAs().setVisible(true);
        }else{
            //False condition
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void tampilGrafikPembelian (){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        try {
            // Query SQL untuk mengambil data dari tabel transaksi_pembelian
            String query = "SELECT nama_obat, jumlah_beli FROM transaksi_pembelian";
            PreparedStatement stmt = connection.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();

            // Menambahkan data ke dataset
            while (rs.next()) {
                String nama_obat = rs.getString("nama_obat");
                int jumlah_beli = rs.getInt("jumlah_beli");
                dataset.addValue(jumlah_beli, "Jumlah", nama_obat);
            }

            // Membuat grafik bar menggunakan dataset
            JFreeChart chart = ChartFactory.createBarChart("Grafik Pembelian Obat", "Nama Obat", "Jumlah", dataset);

            // Membuat panel grafik dan menambahkannya ke panel grafikPanel
            ChartPanel chartPanel = new ChartPanel(chart);
            chartPanel.setPreferredSize(new Dimension(500, 500)); // Mengatur ukuran panel grafik
            grafikPanel.removeAll();
            grafikPanel.add(chartPanel);
            grafikPanel.revalidate();

            // Menutup objek ResultSet dan PreparedStatement
            rs.close();
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }
    }
    
    private void tampilGrafikPenjualan(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        try {
            // Query SQL untuk mengambil data dari tabel transaksi_pembelian
            String query = "SELECT nama_obat, jumlah_jual FROM transaksi_penjualan";
            PreparedStatement stmt = connection.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();

            // Menambahkan data ke dataset
            while (rs.next()) {
                String nama_obat = rs.getString("nama_obat");
                int jumlah_beli = rs.getInt("jumlah_jual");
                dataset.addValue(jumlah_beli, "Jumlah", nama_obat);
            }

            // Membuat grafik bar menggunakan dataset
            JFreeChart chart = ChartFactory.createBarChart("Grafik Penjualan Obat", "Nama Obat", "Jumlah", dataset);

            // Membuat panel grafik dan menambahkannya ke panel grafikPanel
            ChartPanel chartPanel = new ChartPanel(chart);
            chartPanel.setPreferredSize(new Dimension(500, 500)); // Mengatur ukuran panel grafik
            PenjualanPanel.removeAll();
            PenjualanPanel.add(chartPanel);
            PenjualanPanel.revalidate();

            // Menutup objek ResultSet dan PreparedStatement
            rs.close();
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }
    }
    private void grafikPanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_grafikPanelAncestorAdded
        // TODO add your handling code here:
        tampilGrafikPembelian();
    }//GEN-LAST:event_grafikPanelAncestorAdded

    private void PenjualanPanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_PenjualanPanelAncestorAdded
        tampilGrafikPenjualan();
    }//GEN-LAST:event_PenjualanPanelAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatistikData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatistikData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatistikData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatistikData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
        StatistikData statistikData = new StatistikData();
        statistikData.grafikPanelAncestorAdded(null); 
        statistikData.PenjualanPanelAncestorAdded(null);
        statistikData.setVisible(true);
        
    }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PenjualanPanel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMD;
    private javax.swing.JButton btnStatistik;
    private javax.swing.JPanel grafikPanel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel idManagerLabel;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JLabel judulSD;
    private javax.swing.JPanel mainSDPanel;
    private javax.swing.JLabel managerLabel;
    private javax.swing.JPanel medtrackPanelMD;
    private javax.swing.JPanel menupanelMD;
    // End of variables declaration//GEN-END:variables
}
