/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medtrack;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; 
import java.sql.SQLException;
import java.sql.Date;
/**
 *
 * @author LENOVO G40 80
 */
public class Transaksi_Pembelian extends javax.swing.JFrame {
    private Connection connection;
    /**
     * Creates new form Transaksi_Pembelian
     */
    public Transaksi_Pembelian() {
        initComponents();
        connection = KoneksiApo.getKoneksi();
        fetchData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        menuPanelTP = new javax.swing.JPanel();
        idTPPanel = new javax.swing.JPanel();
        ApoLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        TransaksiBtn = new javax.swing.JButton();
        ManagemenObatBtn = new javax.swing.JButton();
        ManagemenSupplierBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        mainPanelTP = new javax.swing.JPanel();
        PembelianBtn = new javax.swing.JButton();
        PenjualanBtn = new javax.swing.JButton();
        kadaluarsaMD = new javax.swing.JButton();
        urutkanMD = new javax.swing.JLabel();
        idObatMD = new javax.swing.JButton();
        stockMD = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        RiwayatTable = new javax.swing.JTable();
        tambaheditPanel = new javax.swing.JPanel();
        TambahBtn1 = new javax.swing.JButton();
        idObatLabel = new javax.swing.JLabel();
        id_transaksiLabel = new javax.swing.JLabel();
        jumlahBeliLabel = new javax.swing.JLabel();
        totalHargaLabel = new javax.swing.JLabel();
        hrg_beliLabel = new javax.swing.JLabel();
        id_transaksiField = new javax.swing.JTextField();
        id_obatField = new javax.swing.JTextField();
        jumlahField = new javax.swing.JTextField();
        totalField = new javax.swing.JTextField();
        hrgBeliField = new javax.swing.JTextField();
        EditBtn1 = new javax.swing.JButton();
        HpsBtn = new javax.swing.JButton();
        ReserBtn = new javax.swing.JButton();
        tgl_beliField = new javax.swing.JTextField();
        tglBeliLabel = new javax.swing.JLabel();
        namaObatLabel1 = new javax.swing.JLabel();
        nama_obatField = new javax.swing.JTextField();
        TambahDataObatLabel1 = new javax.swing.JLabel();
        btnTotalHargaBeli = new javax.swing.JButton();
        judulTabelRiwayat = new javax.swing.JLabel();
        cariTP = new javax.swing.JTextField();
        cariLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));

        menuPanelTP.setBackground(new java.awt.Color(0, 93, 146));

        idTPPanel.setBackground(new java.awt.Color(0, 93, 146));
        idTPPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ApoLabel.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        ApoLabel.setForeground(new java.awt.Color(255, 255, 255));
        ApoLabel.setText("Apoteker A");

        idLabel.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 255, 255));
        idLabel.setText("ID Karyawan");

        javax.swing.GroupLayout idTPPanelLayout = new javax.swing.GroupLayout(idTPPanel);
        idTPPanel.setLayout(idTPPanelLayout);
        idTPPanelLayout.setHorizontalGroup(
            idTPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idTPPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(idTPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel)
                    .addComponent(ApoLabel))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        idTPPanelLayout.setVerticalGroup(
            idTPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idTPPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ApoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        TransaksiBtn.setBackground(new java.awt.Color(52, 152, 219));
        TransaksiBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TransaksiBtn.setForeground(new java.awt.Color(255, 255, 255));
        TransaksiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transaksi.png"))); // NOI18N
        TransaksiBtn.setText("Transaksi");
        TransaksiBtn.setIconTextGap(20);
        TransaksiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiBtnActionPerformed(evt);
            }
        });

        ManagemenObatBtn.setBackground(new java.awt.Color(0, 93, 146));
        ManagemenObatBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManagemenObatBtn.setForeground(new java.awt.Color(255, 255, 255));
        ManagemenObatBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/medicine-icon-29791.png"))); // NOI18N
        ManagemenObatBtn.setText("Management Obat");
        ManagemenObatBtn.setIconTextGap(20);
        ManagemenObatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagemenObatBtnActionPerformed(evt);
            }
        });

        ManagemenSupplierBtn.setBackground(new java.awt.Color(0, 93, 146));
        ManagemenSupplierBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManagemenSupplierBtn.setForeground(new java.awt.Color(255, 255, 255));
        ManagemenSupplierBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supplier.png"))); // NOI18N
        ManagemenSupplierBtn.setText("Managemen Supplier");
        ManagemenSupplierBtn.setIconTextGap(20);
        ManagemenSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagemenSupplierBtnActionPerformed(evt);
            }
        });

        LogoutBtn.setBackground(new java.awt.Color(204, 204, 204));
        LogoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        LogoutBtn.setText("Logout");
        LogoutBtn.setIconTextGap(10);
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        logoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medtrackicon/medtrack.png"))); // NOI18N
        logoLabel.setText("MedTrack");

        javax.swing.GroupLayout menuPanelTPLayout = new javax.swing.GroupLayout(menuPanelTP);
        menuPanelTP.setLayout(menuPanelTPLayout);
        menuPanelTPLayout.setHorizontalGroup(
            menuPanelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(idTPPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuPanelTPLayout.createSequentialGroup()
                .addGroup(menuPanelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelTPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuPanelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ManagemenObatBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TransaksiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManagemenSupplierBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menuPanelTPLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(menuPanelTPLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelTPLayout.setVerticalGroup(
            menuPanelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelTPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTPPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ManagemenObatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TransaksiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ManagemenSupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanelTP.setBackground(new java.awt.Color(255, 255, 255));

        PembelianBtn.setBackground(new java.awt.Color(102, 204, 255));
        PembelianBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PembelianBtn.setForeground(new java.awt.Color(255, 255, 255));
        PembelianBtn.setText("Pembelian");
        PembelianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembelianBtnActionPerformed(evt);
            }
        });

        PenjualanBtn.setBackground(new java.awt.Color(204, 204, 255));
        PenjualanBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PenjualanBtn.setForeground(new java.awt.Color(255, 255, 255));
        PenjualanBtn.setText("Penjualan");
        PenjualanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenjualanBtnActionPerformed(evt);
            }
        });

        kadaluarsaMD.setBackground(new java.awt.Color(46, 204, 113));
        kadaluarsaMD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kadaluarsaMD.setForeground(new java.awt.Color(255, 255, 255));
        kadaluarsaMD.setText("Tanggal Beli");
        kadaluarsaMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kadaluarsaMDActionPerformed(evt);
            }
        });

        urutkanMD.setText("Urutkan");

        idObatMD.setBackground(new java.awt.Color(46, 204, 113));
        idObatMD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idObatMD.setForeground(new java.awt.Color(255, 255, 255));
        idObatMD.setText("id_obat");
        idObatMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idObatMDActionPerformed(evt);
            }
        });

        stockMD.setBackground(new java.awt.Color(46, 204, 113));
        stockMD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stockMD.setForeground(new java.awt.Color(255, 255, 255));
        stockMD.setText("Jumlah Beli");
        stockMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockMDActionPerformed(evt);
            }
        });

        RiwayatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID TRANSAKSI", "ID OBAT", "NAMA OBAT", "TANGGAL ", "HARGA", "JUMLAH", "TOTAL "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        RiwayatTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                RiwayatTableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        RiwayatTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RiwayatTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(RiwayatTable);

        tambaheditPanel.setBackground(new java.awt.Color(255, 255, 255));
        tambaheditPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tambaheditPanel.setMaximumSize(null);

        TambahBtn1.setBackground(new java.awt.Color(102, 204, 255));
        TambahBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TambahBtn1.setText("Tambah");
        TambahBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahBtn1ActionPerformed(evt);
            }
        });

        idObatLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idObatLabel.setText("ID OBAT");

        id_transaksiLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id_transaksiLabel.setText("ID TRANSAKSI");

        jumlahBeliLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jumlahBeliLabel.setText("JUMLAH BELI");

        totalHargaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalHargaLabel.setText("TOTAL HARGA");

        hrg_beliLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hrg_beliLabel.setText("HARGA BELI");

        id_transaksiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_transaksiFieldActionPerformed(evt);
            }
        });

        id_obatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_obatFieldActionPerformed(evt);
            }
        });

        jumlahField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahFieldActionPerformed(evt);
            }
        });

        totalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFieldActionPerformed(evt);
            }
        });

        hrgBeliField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgBeliFieldActionPerformed(evt);
            }
        });

        EditBtn1.setBackground(new java.awt.Color(102, 204, 255));
        EditBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditBtn1.setText("Edit");
        EditBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtn1ActionPerformed(evt);
            }
        });

        HpsBtn.setBackground(new java.awt.Color(102, 204, 255));
        HpsBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HpsBtn.setText("Hapus");
        HpsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HpsBtnActionPerformed(evt);
            }
        });

        ReserBtn.setBackground(new java.awt.Color(102, 204, 255));
        ReserBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReserBtn.setText("Reset");
        ReserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserBtnActionPerformed(evt);
            }
        });

        tgl_beliField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_beliFieldActionPerformed(evt);
            }
        });

        tglBeliLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tglBeliLabel.setText("TANGGAL BELI");

        namaObatLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        namaObatLabel1.setText("NAMA OBAT");

        nama_obatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_obatFieldActionPerformed(evt);
            }
        });

        TambahDataObatLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TambahDataObatLabel1.setText("Tambah Data Obat");

        btnTotalHargaBeli.setBackground(new java.awt.Color(102, 204, 255));
        btnTotalHargaBeli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTotalHargaBeli.setText("Hitung");
        btnTotalHargaBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalHargaBeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambaheditPanelLayout = new javax.swing.GroupLayout(tambaheditPanel);
        tambaheditPanel.setLayout(tambaheditPanelLayout);
        tambaheditPanelLayout.setHorizontalGroup(
            tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambaheditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambaheditPanelLayout.createSequentialGroup()
                        .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambaheditPanelLayout.createSequentialGroup()
                                .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(totalHargaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tglBeliLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tgl_beliField, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tambaheditPanelLayout.createSequentialGroup()
                                        .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnTotalHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(tambaheditPanelLayout.createSequentialGroup()
                                .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tambaheditPanelLayout.createSequentialGroup()
                                        .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jumlahBeliLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(hrg_beliLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(41, 41, 41))
                                    .addGroup(tambaheditPanelLayout.createSequentialGroup()
                                        .addComponent(id_transaksiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jumlahField, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_transaksiField, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31))
                    .addGroup(tambaheditPanelLayout.createSequentialGroup()
                        .addComponent(TambahBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EditBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HpsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ReserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tambaheditPanelLayout.createSequentialGroup()
                        .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hrgBeliField, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(tambaheditPanelLayout.createSequentialGroup()
                                    .addComponent(idObatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(id_obatField, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(tambaheditPanelLayout.createSequentialGroup()
                                    .addComponent(namaObatLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nama_obatField, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(tambaheditPanelLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(TambahDataObatLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tambaheditPanelLayout.setVerticalGroup(
            tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambaheditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TambahDataObatLabel1)
                .addGap(29, 29, 29)
                .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(id_transaksiField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_transaksiLabel))
                .addGap(11, 11, 11)
                .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idObatLabel)
                    .addComponent(id_obatField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nama_obatField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaObatLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrg_beliLabel)
                    .addComponent(hrgBeliField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahBeliLabel))
                .addGap(18, 18, 18)
                .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTotalHargaBeli, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalHargaLabel)
                        .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgl_beliField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglBeliLabel))
                .addGap(43, 43, 43)
                .addGroup(tambaheditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TambahBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HpsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        judulTabelRiwayat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        judulTabelRiwayat.setText("Tabel Riwayat Pembelian");

        cariTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTPActionPerformed(evt);
            }
        });
        cariTP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariTPKeyReleased(evt);
            }
        });

        cariLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cariLabel.setText("Cari");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Transaksi Pembelian");

        javax.swing.GroupLayout mainPanelTPLayout = new javax.swing.GroupLayout(mainPanelTP);
        mainPanelTP.setLayout(mainPanelTPLayout);
        mainPanelTPLayout.setHorizontalGroup(
            mainPanelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelTPLayout.createSequentialGroup()
                .addGroup(mainPanelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PembelianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelTPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tambaheditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(mainPanelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelTPLayout.createSequentialGroup()
                        .addGroup(mainPanelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelTPLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(cariLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cariTP, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelTPLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(PenjualanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(618, Short.MAX_VALUE))
                    .addGroup(mainPanelTPLayout.createSequentialGroup()
                        .addGroup(mainPanelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelTPLayout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(judulTabelRiwayat))
                            .addGroup(mainPanelTPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(mainPanelTPLayout.createSequentialGroup()
                .addGroup(mainPanelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelTPLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(urutkanMD)
                        .addGap(12, 12, 12)
                        .addComponent(kadaluarsaMD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idObatMD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stockMD))
                    .addGroup(mainPanelTPLayout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelTPLayout.setVerticalGroup(
            mainPanelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelTPLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(mainPanelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PembelianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PenjualanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urutkanMD)
                    .addComponent(kadaluarsaMD)
                    .addComponent(idObatMD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockMD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tambaheditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelTPLayout.createSequentialGroup()
                        .addComponent(judulTabelRiwayat)
                        .addGap(24, 24, 24)
                        .addGroup(mainPanelTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cariTP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(375, 375, 375))
        );

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(menuPanelTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanelTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanelTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanelTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TransaksiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiBtnActionPerformed
        // TODO add your handling code here:
        new Transaksi_Pembelian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TransaksiBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin akan keluar?", "PERINGATAN", dialogBtn);

        if(dialogResult==0){
            //True condition
            System.exit(0);
        }else{
            //False condition
        }
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void PembelianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembelianBtnActionPerformed
        // TODO add your handling code here:
        new Transaksi_Pembelian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PembelianBtnActionPerformed

    //SORTING KADALUARSA
    public void sortingTanggalBeli(String tgl_pembelian) {
    DefaultTableModel model = new DefaultTableModel(
       new Object[]{"ID TRANSAKSI","ID OBAT", "NAMA_OBAT", "TANGGAL BELI", "HARGA BELI", "JUMLAH BELI", "TOTAL HARGA"}, 0
        );
    RiwayatTable.setModel(model);

    try {
        Statement statement = connection.createStatement();
        String query = "SELECT * FROM transaksi_pembelian ORDER BY " + tgl_pembelian;
        ResultSet resultSet = statement.executeQuery(query);

        while (resultSet.next()) {
            String kolom1 = resultSet.getString("id_pembelian"); 
                String kolom2 = resultSet.getString("id_obat"); 
                String kolom3 = resultSet.getString("nama_obat"); 
                String kolom4 = resultSet.getString("tgl_pembelian"); 
                int kolom5 = resultSet.getInt("hrg_beli");
                int kolom6 = resultSet.getInt("jumlah_beli"); 
                int kolom7 = resultSet.getInt("total_HrgBeli"); 

                model.addRow(new Object[]{kolom1, kolom2, kolom3, kolom4, kolom5, kolom6, kolom7});
        }

        resultSet.close();
        statement.close();
    } catch (SQLException e) {
         JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }
}
    
     // SORTING ID OBAT
    public void sortingObat(String id_obat) {
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID TRANSAKSI","ID OBAT", "NAMA_OBAT", "TANGGAL BELI", "HARGA BELI", "JUMLAH BELI", "TOTAL HARGA"}, 0
        );
        RiwayatTable.setModel(model);

        try {
            Statement statement = connection.createStatement();
            String query = "SELECT * FROM transaksi_pembelian ORDER BY id_obat";
            ResultSet resultSet = statement.executeQuery(query);

            while (resultSet.next()) {
                String kolom1 = resultSet.getString("id_pembelian"); 
                String kolom2 = resultSet.getString("id_obat"); 
                String kolom3 = resultSet.getString("nama_obat"); 
                String kolom4 = resultSet.getString("tgl_pembelian"); 
                int kolom5 = resultSet.getInt("hrg_beli");
                int kolom6 = resultSet.getInt("jumlah_beli"); 
                int kolom7 = resultSet.getInt("total_HrgBeli"); 

                model.addRow(new Object[]{kolom1, kolom2, kolom3, kolom4, kolom5, kolom6, kolom7});
            }

            resultSet.close();
            statement.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mendapatkan data dari database.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // SORTING JUMLAH OBAT
    public void sortingStock(String jumlah_beli) {
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID TRANSAKSI","ID OBAT", "NAMA_OBAT", "TANGGAL BELI", "HARGA BELI", "JUMLAH BELI", "TOTAL HARGA"}, 0
        );
        RiwayatTable.setModel(model);

        try {
            Statement statement = connection.createStatement();
            String query = "SELECT * FROM transaksi_pembelian ORDER BY jumlah_beli";
            ResultSet resultSet = statement.executeQuery(query);

            while (resultSet.next()) {
                String kolom1 = resultSet.getString("id_pembelian"); 
                String kolom2 = resultSet.getString("id_obat"); 
                String kolom3 = resultSet.getString("nama_obat"); 
                String kolom4 = resultSet.getString("tgl_pembelian"); 
                int kolom5 = resultSet.getInt("hrg_beli");
                int kolom6 = resultSet.getInt("jumlah_beli"); 
                int kolom7 = resultSet.getInt("total_HrgBeli"); 

                model.addRow(new Object[]{kolom1, kolom2, kolom3, kolom4, kolom5, kolom6, kolom7});
            }

            resultSet.close();
            statement.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mendapatkan data dari database.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    // PENCARIAN NAMA OBAT
    public void cariDataTP() {
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID TRANSAKSI","ID OBAT", "NAMA_OBAT", "TANGGAL BELI", "HARGA BELI", "JUMLAH BELI", "TOTAL HARGA"}, 0
        );
        RiwayatTable.setModel(model);   
        // Memanggil method koneksi untuk mendapatkan objek Connection
        Connection conn = KoneksiApo.getKoneksi();
        int jumlahRow = RiwayatTable.getRowCount();
        for (int n=0; n<jumlahRow; n++){
            model.removeRow(0);
        }
        String cari = cariTP.getText();
        try{
            String query = "SELECT * FROM transaksi_pembelian WHERE nama_obat LIKE '%"+ cari +"%'";
            PreparedStatement stmt = conn.prepareStatement(query);
            // Menjalankan query SQL untuk mengambil data dari tabel transaksi_pembelian
            ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                String id_pembelian = rs.getString("id_pembelian");
                String id_obat = rs.getString("id_obat");
                String nama_obat = rs.getString("nama_obat");
                String tgl_pembelian = rs.getString("tgl_pembelian");
                int jumlah_beli = rs.getInt("jumlah_beli");
                int total_HrgBeli = rs.getInt("total_HrgBeli");
                int hrg_beli = rs.getInt("hrg_beli");

            // Menambahkan baris baru ke dalam tabel
            model.addRow(new Object[]{id_pembelian, id_obat, nama_obat, tgl_pembelian, jumlah_beli, total_HrgBeli, hrg_beli});
        }
            
        }catch(SQLException e){
            System.out.print(e.getMessage());
            
        }
    }              
    
    private void kadaluarsaMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kadaluarsaMDActionPerformed
        // TODO add your handling code here:
        sortingTanggalBeli("tgl_pembelian");
    }//GEN-LAST:event_kadaluarsaMDActionPerformed

    private void idObatMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idObatMDActionPerformed
        // TODO add your handling code here:
        sortingObat("id_obat");
    }//GEN-LAST:event_idObatMDActionPerformed

    private void stockMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockMDActionPerformed
        // TODO add your handling code here:
        sortingStock("jumlah_beli");
    }//GEN-LAST:event_stockMDActionPerformed

    private void RiwayatTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_RiwayatTableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_RiwayatTableAncestorAdded
    private void RiwayatTableComponentResized(java.awt.event.ComponentEvent evt) {                                            
        fetchData();
    }
    
    private void fetchData() {
   try {
        // Membuat objek PreparedStatement untuk menjalankan query SQL
        PreparedStatement stmt = connection.prepareStatement("SELECT * FROM transaksi_pembelian");

        // Menjalankan query SQL untuk mengambil data dari tabel transaksi_pembelian
        ResultSet rs = stmt.executeQuery();

        // Mendapatkan model tabel dari JTable
        DefaultTableModel model = new DefaultTableModel();

         // Menambahkan kolom-kolom pada model tabel
        model.addColumn("ID PEMBELIAN");
        model.addColumn("ID OBAT");
        model.addColumn("NAMA OBAT");
        model.addColumn("TGL PEMBELIAN");
        model.addColumn("HARGA BELI");
        model.addColumn("JUMLAH BELI");
        model.addColumn("TOTAL HARGA BELI");

        // Menghapus semua baris yang ada pada tabel
        model.setRowCount(0);

        // Iterasi melalui hasil query dan menambahkan data ke dalam tabel
        while (rs.next()) {
            String id_pembelian = rs.getString("id_pembelian");
            String id_obat = rs.getString("id_obat");
            String nama_obat = rs.getString("nama_obat");
            String tgl_pembelian = rs.getString("tgl_pembelian");
            int hrg_beli = rs.getInt("hrg_beli");
            int jumlah_beli = rs.getInt("jumlah_beli");
            int total_HrgBeli = rs.getInt("total_HrgBeli");

            // Menambahkan baris baru ke dalam tabel
            model.addRow(new Object[]{id_pembelian, id_obat, nama_obat, tgl_pembelian,hrg_beli, jumlah_beli, total_HrgBeli});
        }

        // Mengatur model tabel pada komponen JTable
        RiwayatTable.setModel(model);

        // Menutup objek ResultSet dan PreparedStatement
        rs.close();
        stmt.close();
    } catch (SQLException e) {
        // Menampilkan pesan error jika terjadi kesalahan
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }
}
    private void RiwayatTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RiwayatTableMouseClicked
        // TODO add your handling code here:
        // Mendapatkan indeks baris yang dipilih pada tabel
        int selectedRow = RiwayatTable.getSelectedRow();

        // Mendapatkan data dari baris yang dipilih pada tabel
        id_transaksiField.setText(RiwayatTable.getValueAt(selectedRow, 0).toString());
        id_obatField.setText (RiwayatTable.getValueAt(selectedRow, 1).toString());
        nama_obatField.setText(RiwayatTable.getValueAt(selectedRow, 2).toString());
        tgl_beliField.setText( RiwayatTable.getValueAt(selectedRow, 3).toString());
        hrgBeliField.setText(RiwayatTable.getValueAt(selectedRow, 4).toString());
        jumlahField.setText( RiwayatTable.getValueAt(selectedRow, 5).toString());
        totalField.setText(RiwayatTable.getValueAt(selectedRow, 6).toString());
    }//GEN-LAST:event_RiwayatTableMouseClicked

    private void calculateTotal() {
    try {
        int hrgBeli = Integer.parseInt(hrgBeliField.getText());
        int jumlah = Integer.parseInt(jumlahField.getText());
        int total = hrgBeli * jumlah;
        totalField.setText(String.valueOf(total));
    } catch (NumberFormatException e) {
        // Penanganan jika terjadi kesalahan dalam mengonversi input menjadi angka
        totalField.setText("");
    }
}
    private void btnTotalHargaBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalHargaBeliActionPerformed
        // TODO add your handling code here:
        calculateTotal();
    }//GEN-LAST:event_btnTotalHargaBeliActionPerformed

    private void nama_obatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_obatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_obatFieldActionPerformed

    private void tgl_beliFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_beliFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_beliFieldActionPerformed

    private void ReserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserBtnActionPerformed
        // Mengosongkan inputan pada form
        id_transaksiField.setText(" ");
        id_obatField.setText(" ");
        nama_obatField.setText(" ");
        hrgBeliField.setText(" ");
        jumlahField.setText(" ");
        totalField.setText(" ");
        tgl_beliField.setText(" ");
    }//GEN-LAST:event_ReserBtnActionPerformed

    private void HpsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HpsBtnActionPerformed
        // Mendapatkan ID obat yang akan dihapus
        String id_pembelian = id_transaksiField.getText();

        // Memanggil method koneksi untuk mendapatkan objek Connection
        Connection conn = KoneksiApo.getKoneksi();

        try {
            // Membuat objek PreparedStatement dengan query SQL untuk menghapus data
            String query = "DELETE FROM transaksi_pembelian WHERE id_pembelian=?";
            PreparedStatement stmt = conn.prepareStatement(query);

            // Mengisi parameter pada query SQL dengan nilai dari inputan pengguna
            stmt.setString(1, id_pembelian);

            // Menjalankan query SQL untuk menghapus data dari database
            int rowsDeleted = stmt.executeUpdate();

            // Memeriksa apakah data berhasil dihapus
            if (rowsDeleted > 0) {
                // Menampilkan pesan berhasil
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                fetchData(); // Mengambil data terbaru setelah penghapusan
            } else {
                // Menampilkan pesan jika tidak ada data yang dihapus
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
            }

            // Menutup objek PreparedStatement
            stmt.close();
        } catch (SQLException e) {
            // Menampilkan pesan error jika terjadi kesalahan
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_HpsBtnActionPerformed

    private void EditBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtn1ActionPerformed
                                        
   // Mendapatkan data dari inputan pengguna
        String id_pembelian = id_transaksiField.getText();
        String id_obat = id_obatField.getText();
        String nama_obat = nama_obatField.getText();
        String tgl_pembelian = tgl_beliField.getText();
        int jumlah_beli = Integer.parseInt(jumlahField.getText());
        int hrg_beli = Integer.parseInt(hrgBeliField.getText());
        int total_HrgBeli = Integer.parseInt(totalField.getText());

        // Memanggil method koneksi untuk mendapatkan objek Connection
        Connection conn = KoneksiApo.getKoneksi();

        try {
            // Membuat objek PreparedStatement dengan query SQL untuk mengupdate data
            String query = "UPDATE transaksi_pembelian SET id_obat=?, nama_obat=?, tgl_pembelian=?, hrg_beli=?, jumlah_beli=?, total_HrgBeli=? WHERE id_pembelian=?";
            PreparedStatement stmt = conn.prepareStatement(query);

            // Mengisi parameter pada query SQL dengan nilai dari inputan pengguna
            stmt.setString(1, id_obat);
            stmt.setString(2, nama_obat);
            stmt.setString(3, tgl_pembelian);
            stmt.setInt(4, hrg_beli);
            stmt.setInt(5, jumlah_beli);
            stmt.setInt(6, total_HrgBeli);
            stmt.setString(7, id_pembelian);

            // Menjalankan query SQL untuk mengupdate data di database
            int rowsUpdated = stmt.executeUpdate();

            // Memeriksa apakah data berhasil diupdate
            if (rowsUpdated > 0) {
                // Menampilkan pesan berhasil
                JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
                fetchData(); // Mengambil data terbaru setelah update
            } else {
                // Menampilkan pesan jika tidak ada data yang diupdate
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
            }

            // Menutup objek PreparedStatement
            stmt.close();
        } catch (SQLException e) {
            // Menampilkan pesan error jika terjadi kesalahan
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        } catch (NumberFormatException ex) {
            // Menampilkan pesan error jika terjadi kesalahan dalam mengonversi input menjadi angka
            JOptionPane.showMessageDialog(null, "Jumlah beli, harga beli, dan total harga beli harus berupa angka");
        }
    }//GEN-LAST:event_EditBtn1ActionPerformed

    private void hrgBeliFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgBeliFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgBeliFieldActionPerformed

    private void totalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFieldActionPerformed

    private void jumlahFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahFieldActionPerformed

    private void id_obatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_obatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_obatFieldActionPerformed

    private void id_transaksiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_transaksiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_transaksiFieldActionPerformed

    private void validateJumlahObat(int jumlah_obat) throws MyException {
    if (jumlah_obat <= 0) {
        throw new MyException("Jumlah obat harus lebih dari 0", connection);
    }
    }
    
    private void TambahBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahBtn1ActionPerformed
        String id_pembelian = id_transaksiField.getText();
        String id_obat = id_obatField.getText();
        String nama_obat = nama_obatField.getText();
        int hrg_beli;
        int jumlah_beli;
        int total_HrgBeli;

        try {
            hrg_beli = Integer.parseInt(hrgBeliField.getText());
            jumlah_beli = Integer.parseInt(jumlahField.getText());
            total_HrgBeli = Integer.parseInt(totalField.getText());
        } catch (NumberFormatException ex) {
            // Menampilkan pesan error jika terjadi kesalahan dalam mengonversi input menjadi angka
            JOptionPane.showMessageDialog(null, "Total harga dan jumlah transaksi harus berupa angka");
            return; // Menghentikan eksekusi selanjutnya
        }

        String tgl_pembelian = tgl_beliField.getText();

        try {
            // Memvalidasi jumlah obat
            validateJumlahObat(jumlah_beli);

            // Membuat objek PreparedStatement dengan query SQL
            String query = "INSERT INTO transaksi_pembelian (id_pembelian, id_obat, nama_obat, tgl_pembelian, jumlah_beli, hrg_beli, total_HrgBeli) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement stmt = connection.prepareStatement(query);

            // Mengisi parameter pada query SQL dengan nilai dari inputan pengguna
            stmt.setString(1, id_pembelian);
            stmt.setString(2, id_obat);
            stmt.setString(3, nama_obat);
            stmt.setString(4, tgl_pembelian);
            stmt.setInt(5, jumlah_beli);
            stmt.setInt(6, hrg_beli);
            stmt.setInt(7, total_HrgBeli);

            // Menjalankan query SQL untuk menambahkan data ke database
            stmt.executeUpdate();

            // Menampilkan pesan berhasil
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");

            // Menutup objek PreparedStatement
            stmt.close();
            fetchData(); // Memanggil metode fetchData untuk mengambil data terbaru
        } catch (SQLException e) {
            // Menampilkan pesan error jika terjadi kesalahan
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        } catch (MyException ex) {
            // Menampilkan pesan error jika jumlah obat tidak valid
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_TambahBtn1ActionPerformed

    private void PenjualanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenjualanBtnActionPerformed
        // TODO add your handling code here:
        new Transaksi_Penjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PenjualanBtnActionPerformed

    private void ManagemenObatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagemenObatBtnActionPerformed
        // TODO add your handling code here:
        new MObatApoteker().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ManagemenObatBtnActionPerformed

    private void ManagemenSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagemenSupplierBtnActionPerformed
        // TODO add your handling code here:
        new MSupplier().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ManagemenSupplierBtnActionPerformed

    private void cariTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTPActionPerformed
        // TODO add your handling code here:
        cariDataTP();
    }//GEN-LAST:event_cariTPActionPerformed

    private void cariTPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTPKeyReleased
        // TODO add your handling code here:
        cariDataTP();
    }//GEN-LAST:event_cariTPKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi_Pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApoLabel;
    private javax.swing.JButton EditBtn1;
    private javax.swing.JButton HpsBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton ManagemenObatBtn;
    private javax.swing.JButton ManagemenSupplierBtn;
    private javax.swing.JButton PembelianBtn;
    private javax.swing.JButton PenjualanBtn;
    private javax.swing.JButton ReserBtn;
    private javax.swing.JTable RiwayatTable;
    private javax.swing.JButton TambahBtn1;
    private javax.swing.JLabel TambahDataObatLabel1;
    private javax.swing.JButton TransaksiBtn;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnTotalHargaBeli;
    private javax.swing.JLabel cariLabel;
    private javax.swing.JTextField cariTP;
    private javax.swing.JTextField hrgBeliField;
    private javax.swing.JLabel hrg_beliLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idObatLabel;
    private javax.swing.JButton idObatMD;
    private javax.swing.JPanel idTPPanel;
    private javax.swing.JTextField id_obatField;
    private javax.swing.JTextField id_transaksiField;
    private javax.swing.JLabel id_transaksiLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel judulTabelRiwayat;
    private javax.swing.JLabel jumlahBeliLabel;
    private javax.swing.JTextField jumlahField;
    private javax.swing.JButton kadaluarsaMD;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel mainPanelTP;
    private javax.swing.JPanel menuPanelTP;
    private javax.swing.JLabel namaObatLabel1;
    private javax.swing.JTextField nama_obatField;
    private javax.swing.JButton stockMD;
    private javax.swing.JPanel tambaheditPanel;
    private javax.swing.JLabel tglBeliLabel;
    private javax.swing.JTextField tgl_beliField;
    private javax.swing.JTextField totalField;
    private javax.swing.JLabel totalHargaLabel;
    private javax.swing.JLabel urutkanMD;
    // End of variables declaration//GEN-END:variables
}
